
const THIRTY_DAYS_IN_MILLISECONDS = 1000 * 60 * 60 * 24 * 30;
const TEN_DAYS_IN_MILLISECONDS = 1000 * 60 * 60 * 24 * 10;
const TWENTYFOUR_HOURS_IN_MILLISECONDS = 1000 * 60 * 60 * 24;
const THREE_HOURS_IN_MILLISECONDS = 1000 * 60 * 60 * 3;
const ONE_HOUR_IN_MILLISECONDS = 1000 * 60 * 60 * 1;
const FIFTEEN_MINUTES_IN_MILLISECONDS = 1000 * 60 * 15;
const TEN_MINUTES_IN_MILLISECONDS = 1000 * 60 * 10;
const FIVE_MINUTES_IN_MILLISECONDS = 1000 * 60 * 5;
const THREE_MINUTES_IN_MILLISECONDS= 1000 * 60 * 3;
const ONE_MINUTE_IN_MILLISECONDS = 1000 * 60 * 1;
const FIVE_SECONDS_IN_MILLISECONDS = 1000 * 5;
const ONE_SECOND_IN_MILLISECONDS = 1000;
const JWT_FINGERPRINT_SESSION_NAME = 'fingerprint';
const JWT_SECRET = 'l)o0n(2gs$^DF5$21)46(%8%^ec#r#ets9((t^ri)n0g8^39to)%p6r*ev&&e)57nt<^f&r7)om&^76gu5ess^6?60^)55?i<6ng09>0the0>se)ss^i7ons';
const JWT_ACCESS_TOKEN_TOTAL_EXPIRATION_TIME_IN_MILLISECONDS = TEN_MINUTES_IN_MILLISECONDS;

const JWT_REFRESH_TOKEN_TOTAL_EXPIRATION_TIME_IN_MILLISECONDS = ONE_HOUR_IN_MILLISECONDS;
const JWT_REFRESH_TOKEN_UPDATE_FREQUENCY_IN_MILLISECONDS = THREE_MINUTES_IN_MILLISECONDS;
const EXPIRED_JWT_TOKEN_CLEANUP_FREQUENCY_IN_MILLISECONDS = FIVE_MINUTES_IN_MILLISECONDS;



const service = {
    JWT_FINGERPRINT_SESSION_NAME:JWT_FINGERPRINT_SESSION_NAME,
    JWT_SECRET : JWT_SECRET,
    JWT_ACCESS_TOKEN_TOTAL_EXPIRATION_TIME_IN_MILLISECONDS : JWT_ACCESS_TOKEN_TOTAL_EXPIRATION_TIME_IN_MILLISECONDS,
    ONE_SECOND_IN_MILLISECONDS:ONE_SECOND_IN_MILLISECONDS,
    ONE_MINUTE_IN_MILLISECONDS:ONE_MINUTE_IN_MILLISECONDS,
    JWT_REFRESH_TOKEN_TOTAL_EXPIRATION_TIME_IN_MILLISECONDS : JWT_REFRESH_TOKEN_TOTAL_EXPIRATION_TIME_IN_MILLISECONDS,
    JWT_REFRESH_TOKEN_UPDATE_FREQUENCY_IN_MILLISECONDS : JWT_REFRESH_TOKEN_UPDATE_FREQUENCY_IN_MILLISECONDS,
    EXPIRED_JWT_TOKEN_CLEANUP_FREQUENCY_IN_MILLISECONDS : EXPIRED_JWT_TOKEN_CLEANUP_FREQUENCY_IN_MILLISECONDS
}

export default service;