import TokenDuration from'../../src/library/enumerations/TokenDuration.js';


const THREE_DAYS_IN_MILLISECONDS = 1000 * 60 * 60 * 24 * 3;
const TWENTYFOUR_HOURS_IN_MILLISECONDS = 1000 * 60 * 60 * 24;
const THREE_HOURS_IN_MILLISECONDS = 1000 * 60 * 60 * 3;
const FIFTEEN_MINUTES_IN_MILLISECONDS = 1000 * 60 * 15;
const TEN_MINUTES_IN_MILLISECONDS = 1000 * 60 * 10;
const FIVE_MINUTES_IN_MILLISECONDS = 1000 * 60 * 5;
const THREE_MINUTES_IN_MILLISECONDS= 1000 * 60 * 3;
const ONE_MINUTE_IN_MILLISECONDS = 1000 * 60 * 1;
const FIVE_SECONDS_IN_MILLISECONDS = 1000 * 5;
const ONE_SECOND_IN_MILLISECONDS = 1000;

//Token Engine Activated
const ANTIFORGERY_TOKEN_ACTIVATED = TokenDuration.expiringToken;


const ANTIFORGERY_TOKEN_TERMINATION_TIME_IN_MILLISECONDS = TWENTYFOUR_HOURS_IN_MILLISECONDS;
const TERMINATED_ANTIFORGERY_TOKEN_CLEANUP_FREQUENCY_IN_MILLISECONDS = THREE_MINUTES_IN_MILLISECONDS;

const NON_EXPIRING_ANTIFORGERY_TOKEN_SECRET = 's90dDDSOdx435TwaMW932987Sdjkq3f.SokjSD2i70kpiw%$TELopsadf7a.slR6sdqrpoiFAKLDWO';

const EXPIRING_ANTIFORGERY_TOKEN_SECRET    = 'io65ghjrsIolkjwooG5rDFES3Hn78fl9y.kn6t0d6fedfwd33253ow.thisadfdaldkklasdfiuebs';
const EXPIRING_ANTIFORGERY_TOKEN_ACTIVE_TIME_IN_MILLISECONDS = THREE_DAYS_IN_MILLISECONDS;
const EXPIRING_ANTIFORGERY_TOKEN_HASH_LENGTH = 32 //Total Character count
const EXPIRING_ANTIFORGERY_TOKEN_CRYPTO_KEY = 'aQ12poiaf$kjri$sopz@m58f8@hyg9245@#%^&(&$@$^$#&*)$@!$%hdssyg&&433T';


let cryptoKey ='you cannot change this without invalidating the token';




const service = {
    ANTIFORGERY_TOKEN_ACTIVATED : ANTIFORGERY_TOKEN_ACTIVATED,
    ANTIFORGERY_TOKEN_TERMINATION_TIME_IN_MILLISECONDS : ANTIFORGERY_TOKEN_TERMINATION_TIME_IN_MILLISECONDS,
    TERMINATED_ANTIFORGERY_TOKEN_CLEANUP_FREQUENCY_IN_MILLISECONDS : TERMINATED_ANTIFORGERY_TOKEN_CLEANUP_FREQUENCY_IN_MILLISECONDS,
    NON_EXPIRING_ANTIFORGERY_TOKEN_SECRET : NON_EXPIRING_ANTIFORGERY_TOKEN_SECRET,
    EXPIRING_ANTIFORGERY_TOKEN_SECRET : EXPIRING_ANTIFORGERY_TOKEN_SECRET,
    EXPIRING_ANTIFORGERY_TOKEN_ACTIVE_TIME_IN_MILLISECONDS : EXPIRING_ANTIFORGERY_TOKEN_ACTIVE_TIME_IN_MILLISECONDS,
    EXPIRING_ANTIFORGERY_TOKEN_HASH_LENGTH : EXPIRING_ANTIFORGERY_TOKEN_HASH_LENGTH,
    EXPIRING_ANTIFORGERY_TOKEN_CRYPTO_KEY : EXPIRING_ANTIFORGERY_TOKEN_CRYPTO_KEY
}

export default service;